### ISSUE TITLE
你好，请问MRE的代码每次跑的结果都是不一样的，请问是有什么设置导致的结果一直在变化吗，请问如何修改变为固定结果，谢谢！！

### ISSUE THREAD

**Issue by 1411591326** [thecharm/TMR#7]
你好，请问MRE的代码每次跑的结果都是不一样的，请问是有什么设置导致的结果一直在变化吗，请问如何修改变为固定结果，谢谢！！

**Comment by thecharm** [comment]
你好，你可以检查一下看看seed是否设置为一个常数，如果seed固定了，结果应该也是固定的

**Comment by 1411591326** [comment]
> 你好，你可以检查一下看看seed是否设置为一个常数，如果seed固定了，结果应该也是固定的

好的！十分感谢！

**Comment by zjutnlper** [comment]
你好，问一下，反向翻译的图片是要自己生成吗，我看作者好像没有给出
