### ISSUE TITLE
关于论文中对比实验的疑问?

### ISSUE THREAD

**Issue by jiaweidoris** [thecharm/TMR#8]
您好，非常感谢您卓越的工作。打扰您一下，我想问，关于论文中的对比实验的您的另一个工作MEGA，该文章《Multimodal Relation Extraction with Efficient Graph Alignment》的原文只有多模态关系抽取的实验结果，没有关于多模态命名实体识别（MNER）的实验数据结果，而且原项目也没有提供关于MNER的数据集处理之后的数据结果（比如imgSG，rel_1等数据）和MNER的代码，请问您是如何修改代码得到结果的呢？请问可以提供一下MNER的代码和MNER数据集处理之后的结果（比如imgSG，rel_1等数据）吗？

**Comment by thecharm** [comment]
您好，我们并没有复现MEGA在MNER上的实验结果，这个结果我们直接参考HVPNeT论文，原代码和论文可以在这里找到https://github.com/zjunlp/HVPNeT

**Comment by jiaweidoris** [comment]
> 您好，我们并没有复现MEGA在MNER上的实验结果，这个结果我们直接参考HVPNeT论文，原代码和论文可以在这里找到https://github.com/zjunlp/HVPNeT

好的谢谢您
